# Use a specific NGINX version
ARG NGINX_VERSION=1.25.4-alpine-slim
FROM nginx:$NGINX_VERSION

# Argument for custom NGINX command
ARG NGINX_CMD
ENV NGINX_CMD=${NGINX_CMD:-nginx}

#Adjustments to Nginx Configuration
COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf

# Install necessary packages
RUN apk update && apk add vim nano shadow

# Create a non-root user and group if they don't exist
RUN if ! getent group www-data; then addgroup -S www-data; fi && \
    if ! id -u www-data; then adduser -S -G www-data -u 44444 www-data; else usermod -u 44444 www-data; fi

# Ensure correct ownership of directories
RUN mkdir -p /var/cache/nginx /var/run /var/log/nginx && \
    touch /var/run/nginx.pid && \
    chown -R www-data:www-data /var/cache/nginx /var/run /var/log/nginx /etc/nginx /var/run/nginx.pid

# Switch to the non-root user
USER www-data

# Expose the port
EXPOSE 8080

# Command to run NGINX
CMD ${NGINX_CMD} -g "daemon off;"